args:
  aux_loss: 0.0
  base_path: Null
  batch_size: 128
  beta2: 0.999
  checkpoint_dir: Null
  cycle: 1,
  data_split: default
  dataset_name: drugs
  decoder_layers: Null
  decoder_std: 1.0
  device: 0
  dropedge_rate: 0.1
  dropnode_rate: 0.1
  dropout: 0.1
  enable_tb: false
  encoder_dropout: 0.0
  epochs: 100
  eval_from: script/dmcg/checkpoint_94.pt
  eval_one: false
  extend_edge: false
  global_attn: false
  global_reducer: sum
  graph_pooling: sum
  input_file: Null
  latent_size: 256
  layernorm_before: false
  log_interval: 100
  lr: 0.0001
  lr_warmup: false
  mlp_hidden_size: 1024
  mlp_layers: 2
  node_attn: true
  node_reducer: sum
  noise_level: 10
  noise_lr: 2.4e-06
  noise_steps: 100
  num_layers: 6
  num_workers: 0
  out: Null
  period: 10
  pred_pos_residual: true
  prop_pred: false
  remove_hs: true
  reuse_prior: true
  sample_beta: 1.2
  score: false
  score_prior: false
  seed: 2022
  shared_decoder: false
  shared_output: true
  sigma_begin: 10.0
  sigma_end: 0.01
  smiles: ''
  threshold: 0.5
  train_size: 0.8
  train_subset: true
  use_adamw: true
  use_bn: true
  use_ff: false
  use_global: false
  use_layer_norm: false
  vae_beta: 1.0
  weight_decay: 0.01
  workers: 1

shared_params:
  mlp_hidden_size: 1024
  mlp_layers: 2
  latent_size: 256
  use_layer_norm: false
  num_message_passing_steps: 6
  global_reducer: sum
  node_reducer: sum
  dropedge_rate: 0.1
  dropnode_rate: 0.1
  dropout: 0.1
  layernorm_before: false
  encoder_dropout: 0.0
  use_bn: true
  vae_beta: 1.0
  decoder_layers: Null
  reuse_prior: true
  cycle: 1
  pred_pos_residual: true
  node_attn: true
  global_attn: false
  shared_decoder: false
  sample_beta: 1.2
  shared_output: true
