train:
  batch_size: 128
  seed: 2022
  epochs: 300  
  shuffle: true
  resume_train: false
  eval: true
  num_workers: 0
  gpus:
    - 0
    - Null
    - Null
    - Null
  anneal_power: 2.0
  save: true
  save_path: ./train
  resume_checkpoint: null
  resume_epoch: null
  log_interval: 400
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 0.000
    dropout: 0.0
  scheduler:
    type: plateau
    factor: 0.6
    # factor: 0.95
    patience: 10
    min_lr: 1e-4
    

test:
  init_checkpoint: ./train/drugs_default
  output_path: ./test
  epoch: 38
  gen:
    dg_step_size: 3.0
    dg_num_steps: 1000  
    steps_d: 100
    step_lr_d: 0.000002
    steps_pos: 100
    step_lr_pos: 0.0000024
    clip: 1000
    min_sigma: 0.0
    verbose: 1


data:
  base_path: ../../../structure/GEOM/script/geomol/confgf
  dataset: drugs
  train_set: train_data_205k.pkl
  val_set: val_data_25k.pkl
  test_set: test_data_25k.pkl

  
model:
  name: drugs_default
  hidden_dim: 256
  num_convs: 4
  sigma_begin: 10
  sigma_end: 0.01
  num_noise_level: 50
  order: 3
  mlp_act: relu
  gnn_act: relu
  cutoff: 10.0
  short_cut: true
  concat_hidden: false   
  noise_type: symmetry
  edge_encoder: mlp
